server:
  port: 8849

spring:
  application:
    name: oa-business-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:nacos:${spring.application.name}.yaml?group=OA_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:x}

management:
  endpoints:
    web:
      exposure:
        include: health,info
